install:
- gem install asciidoctor
- gem install coderay
- gem install link-checker
script:
- asciidoctor -a icons -a linkcss! -a numbered faq.adoc -o html/index.html 
- asciidoctor -a icons -a linkcss! -a numbered page2.adoc -o html/page2.html 
- asciidoctor -a icons -a linkcss! -a numbered page3.adoc -o html/page3.html 
- rake check_links
- rake test
sudo: true
env:
  global:
  - GH_REF: Dorlige/ProjetIntegrationContinue.git
  -COMMIT_IGNORE_BUILD="autocommiting new file [ci skip]"
  - secure: GB0dA0X07qe8P2Y93PM0IfcYdMupzBM2KTMOb6skTXGDwfdgnBovAw1RMuT2Urh19DTK/U7f+AJNkZbTvcgN3J6s7vAFzQxqVgcepXdgcvp+BoZxflYa0oKCqwm0cgMvz+6E5t1qcY2zCXsdmFsNNbjujAg054vV54yrut7NnWNqgtaHp/JxyOUB3hGRNTZCPIb+JkE1b+fGKA4pckoY/HV1901IOYcEqWYsGwD06rauSJb/SGxhJ/CmEuKf+7ZuVgmIhUTCT3F6lpEfZ0zn4MqnfBPgv1LuqIxQ6TXNPHHvoy7GtntFv2mqEnuqGq3s0Aq7v1RrovBNNoD9oGs5WaAg1KmidZp2ye9JQ7VLQof+jYUDRgkQgJe/FUeaaec2DSmuNYICZ8MpP3iVPhXWJutyUK7aedKCUoy6hfr5QYCKvg8rXtvSrjEgfZGcLQDWRUSIZig6rDPNTYrA+nc6/TjjQrpo6aZUPHxZqMwvP3I7GdqMGMfC9R5+v/2fYiaQlUs0+60zAOk5lqaBvPXA6ftrok64Xh+XwRWTteiBqnBSL3R+CbD0wGMM6qLiuPQ+a1HJMC0G+8M7vROIZMUFzuVvzvVTgqc8xtGS8hV70D+YF4sUmfSKEMKjjb/9JqHpgQVUoQdDUrIczfG6N3bz9ylW2bsPGS0LC0gr79xlsKc=
after_success:
- bash monscript.sh
